union withsource = tt *
| where TimeGenerated > ago(1d)
| where _IsBillable == true
| where tt == "AzureDiagnostics" and ResourceProvider == "MICROSOFT.LOGIC"
| summarize GBytes=round(sum(_BilledSize/1024/1024/1024),2)
 by Solution=tt , _IsBillable , SubscriptionId, ResourceGroup, _ResourceId, Resource, ResourceProvider, Category, ResourceType, OperationName, resource_actionName_s
| extend ResourceName = split(_ResourceId, '/')[8]
| sort by GBytes